version: "3"
services:
  monerod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18081"
      - "18080:18080"
      - "28080:28080"
      - "28081"
    volumes:
      - monerod:/opt/monero
    stdin_open: true
    command: bash -c "./monerod --testnet --config-file /opt/monero/monerod.conf --rpc-bind-ip 0.0.0.0 --confirm-external-bind"
  rpc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "138.68.53.57:18081:18081"
    stdin_open: true
    command: bash -c "./monero-wallet-rpc --testnet --daemon-host monerod --rpc-bind-port 18081 --confirm-external-bind --rpc-login username:password --log-level 4 --wallet-file /opt/monero/testnet-wallet --password 21belair"
    volumes:
      - monerod:/opt/monero
    links:
      - monerod
  wallet-cli:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    command: bash -c "./monero-wallet-cli --testnet --generate-new-wallet /opt/monero/testnet-wallet"
    volumes:
      - monerod:/opt/monero
volumes:
  monerod:
